### ISSUE TITLE
Character Selection Bug fixes and improvements

### ISSUE THREAD

**Issue by Swimmer215** [LaGamma/WalrusWars#111]
Player portraits are initialized with a fill color that makes them go invisible until a color is selected. If the game is started without selecting a color the bots will be invisible.

Players are both assigned the color that is selected for player 1

Currently can't edit the name field, its a little complicated to implement because it needs to be nested inside the event system

Colors should probably be tweaked

Kind of weird that player 1 gets to choose all the options

**Comment by LaGamma** [comment]
bugs here have been fixed! on inspection stage.generateMap() was overwriting memory of the walrus data which was causing problems with player 2 but now Players and Stage are packed in smart pointers which fixes this issue - I don't think I'll be able to get to name editor or player2 character selection (but most people likely wont have gamepads to play with anyway and double keyboard selection would be a bit clunky unless we mimicked the walrus attack so I think we're good there)
