### ISSUE TITLE
collision bug, text bug, animation fix

### ISSUE THREAD

**Issue by Swimmer215** [LaGamma/WalrusWars#42]
Collision bug: Walruses get tethered to each other. To recreate, as soon as the game starts you hit S and UP ARROW at the same time until the collisions go to nearly zero and the walruses are just running into each other without bouncing off. Unlikely it would be recreated in an actual two player match.

text bug: I noticed the winning screen text is off if you go to full screen

animation fix: reset walruses to their default sprite after each round instead of staying on last sprite displayed from previous round. Fix walrus side slide sprite being cut off by circle.

**Comment by LaGamma** [comment]
Thanks for documenting these! The tethering bug is pretty funny - @Reid-Nagurka @yushjoshi @swimmer215 if you have a chance to solve any of these, assign yourself to this issue and comment which one you're working on

**Comment by Reid-Nagurka** [comment]
I'll work on text bug and animation. I thought I fixed the animation issue but I'll double check (may have forgotten to push).

**Comment by LaGamma** [comment]
The walrus sprites are now RectangleShapes to prevent cutoff and I added a small bit of knockback with each collision so they don't tether together.
